### ISSUE TITLE
Archive themes float with window at a certain width

### ISSUE THREAD

**Issue by a-murry** [uofo/reverse-archaeology#31]
In both Safari and Chrome, Archive Main Page (card catalog) themes float and overlap when window is at a certain width.
<img width="1015" alt="screen shot 2017-03-20 at 5 56 43 pm" src="https://cloud.githubusercontent.com/assets/20864185/24123656/c9d19754-0d96-11e7-805a-12780fcf65ab.png">

**Comment by ebrelsford** [comment]
@a-murry I've fixed this, but it's not perfect--if you're resizing the browser it can still get a little funky. But there should no longer be a browser width that is this weird if you reload the page. Assuming this is fine because for the most part people aren't going to be resizing the screen this way, but let me know if not.
